### PR TITLE
Waves upd

### PR DESCRIPTION
**Pull request by VladimirLevv**

### CODE REVIEW

**Comment by akhavr** [comment]
Closes #67

**Comment by VladimirLevv** [comment]
He names himself "Sasha" everywhere.

**Comment by VladimirLevv** [comment]
Also, project is called WavesPlatform. Waves is a name of cryptocurrency

**Comment by akhavr** [comment]
> He names himself "Sasha" everywhere.

I know, I've met him.

> Also, project is called WavesPlatform. Waves is a name of cryptocurrency

ok

**Pull request merged**
